// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretSanta.Domain.Data;

#nullable disable

namespace SecretSanta.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20211121223847_AddMetadata")]
    partial class AddMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SecretSanta.Domain.Data.SqliteDbContext+PersistedSantaEvent", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Uid");

                    b.ToTable("santa_event", (string)null);
                });

            modelBuilder.Entity("SecretSanta.Domain.Data.SqliteDbContext+PersistedSantaEventMembership", b =>
                {
                    b.Property<string>("EventUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_uid");

                    b.Property<string>("TelegramLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("telegram_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OpponentTelegramLogin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opponent_telegram_login");

                    b.HasKey("EventUid", "TelegramLogin");

                    b.HasIndex("TelegramLogin", "EventUid");

                    b.ToTable("santa_event_membership", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
