//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretSanta.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecretSanta_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecretSanta_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecretSanta.Resources.SecretSanta.uk", typeof(SecretSanta_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код цього застосунку у відкритому доступі. Код можна знайти у .
        /// </summary>
        internal static string AppIsOpenSource {
            get {
                return ResourceManager.GetString("AppIsOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви даруєте подарунок.
        /// </summary>
        internal static string BuyPresentFor {
            get {
                return ResourceManager.GetString("BuyPresentFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця подія не активна. Сторінка залишилась тільки для історії..
        /// </summary>
        internal static string EventArchived {
            get {
                return ResourceManager.GetString("EventArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дана подія не знайдена.
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизуватись за допомогою Telegram.
        /// </summary>
        internal static string LoginWithTelegram {
            get {
                return ResourceManager.GetString("LoginWithTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джерело картинок.
        /// </summary>
        internal static string PictureCredits {
            get {
                return ResourceManager.GetString("PictureCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До вашої уваги, для цієї події &lt;b&gt;рекомендована максимальна ціна&lt;/b&gt; для подарунку виставлена як.
        /// </summary>
        internal static string RecommendedMaxPriceIs {
            get {
                return ResourceManager.GetString("RecommendedMaxPriceIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо у вас виникли проблеми із сайтом, можете спробувати знайти кому дарувати подаркунки у телеграм боті.
        /// </summary>
        internal static string TryTelegramBot {
            get {
                return ResourceManager.GetString("TryTelegramBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви авторизовані як.
        /// </summary>
        internal static string YouAreLoggedIn {
            get {
                return ResourceManager.GetString("YouAreLoggedIn", resourceCulture);
            }
        }
    }
}
